### ISSUE TITLE
Game crashes when opening inventory

### ISSUE THREAD

**Issue by samuelh2005** [Fexcraft/PlainCarsPack#1]
When I have the Plain Cars Pack enabled, and I open my inventory the game crashes. If I disable the Plan Cars Pack I can open my inventory just fine.

## Mods:
* Fex's Vehicle & Transportation Mod (4.20.12)
* Fex's Vehicle pack (3.1.2b)
* Fexcraft Common Library (20.11.c)
* General Essentials Pack (3.1.1)
* Plan Cars Pack (1.1)

**All other mods in the pack have been disabled**

## Minecraft:
- 1.20.1 (can't use a newer version due to Create)
- Forge 47.3.10

## Logs
- `latest.log`: https://mclo.gs/idbYPKZ
- `crash-***-log`: https://mclo.gs/uZ5dO0T

**Comment by Fexcraft** [comment]
Sorry for the late reply, I was not checking on the GitHub website.
The issue seems fixed in FVTM but the fix was not uploaded, I'll do that now.
This is not an issue with PlainCarsPack itself.

**Comment by samuelh2005** [comment]
Thanks, can confirm the bug is fixed!
